Repository vuejs-jp/ja.vuejs.org, pull requests merged in 2020-12, with the labels that each got.

#171 doc: Tranlate list transition
  src/guide/transitions-list.md
Labels: PR: unreviewed

#170 docs: ガワだけ翻訳
  src/.vuepress/config.js
  src/.vuepress/theme/components/Newsletter.vue
  src/.vuepress/theme/components/sponsors/OpenCollectiveSponsors.vue
  src/.vuepress/theme/components/sponsors/PatreonSponsors.vue
  src/.vuepress/theme/components/sponsors/SpecialSponsors.vue
  src/README.md
  src/api/application-api.md
  src/api/application-config.md
  src/api/built-in-components.md
  src/api/directives.md
  src/api/global-api.md
  src/api/instance-methods.md
  src/api/instance-properties.md
  src/api/special-attributes.md
  src/guide/a11y-resources.md
Labels: PR: reviewed-approved

#172 docs(example): Translate examples
  src/examples/commits.md
  src/examples/elastic-header.md
  src/examples/grid-component.md
  src/examples/markdown.md
  src/examples/modal.md
  src/examples/select2.md
  src/examples/svg.md
  src/examples/todomvc.md
  src/examples/tree-view.md
Labels: PR: partially-approved

#174 docs(guide): Tranlate reactivitiy computed watchers
  src/guide/reactivity-computed-watchers.md
Labels: PR: reviewed-approved

#176 doc: エコシステム全体の翻訳
  src/.vuepress/components/community/team/index.vue
  src/.vuepress/components/community/themes/index.vue
  src/.vuepress/components/community/themes/theme-data.js
  src/community/join.md
  src/community/partners.md
  src/community/team.md
  src/community/themes.md
Labels: PR: reviewed-approved

#179 doc: Translate application api
  src/api/application-api.md
Labels: PR: unreviewed

#178 doc: Translate API Configuration in Reference
  src/api/application-config.md
Labels: PR: unreviewed

#168 translate style guide priority b (#138)
  src/style-guide/README.md
Labels: PR: reviewed-approved
