Repository vuejs-jp/ja.vuejs.org, pull requests merged in 2020-10, with the labels that each got.

#98 docs: Essentials > Components Basics の翻訳 #11
  src/guide/component-basics.md
Labels: PR: reviewed-approved

#100 chore: Temporary disable tag alert actions
  .github/workflows/pr.yaml
Labels: PR: unreviewed

#101 Advanced Guides > Compotion API > Introduction の翻訳
  src/guide/composition-api-introduction.md
Labels: PR: partially-approved

#103 test: Execute TextLint on CI
  .github/workflows/ja.yaml
  src/guide/a11y-resources.md
  src/guide/a11y-semantics.md
  src/guide/a11y-standards.md
  src/guide/events.md
  src/guide/forms.md
  src/guide/instance.md
  src/guide/introduction.md
  src/guide/migration/attribute-coercion.md
  src/guide/migration/global-api-treeshaking.md
  src/guide/migration/global-api.md
  src/guide/optimizations.md
  src/guide/plugins.md
  src/guide/render-function.md
  src/guide/single-file-component.md
  src/guide/template-syntax.md
Labels: PR: reviewed-approved

#102 Transitions & Animation > Enter & Leave Transitions の翻訳
  package.json
  src/guide/transitions-enterleave.md
Labels: PR: reviewed-approved

#105 Components In-Depth > Slots の翻訳
  src/guide/component-slots.md
Labels: PR: reviewed-approved

#104 Transitions & Animation > Overview の翻訳
  src/guide/transitions-overview.md
Labels: PR: reviewed-approved

#135 Migration Guide > Events API の翻訳
  src/guide/migration/events-api.md
Labels: PR: reviewed-approved

#133 Translate: Migration Guide > Fragments
  src/guide/migration/fragments.md
Labels: PR: reviewed-approved

#136 Docs > Translations の翻訳
  src/guide/contributing/translations.md
Labels: PR: reviewed-approved

#137 chore: Add CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: PR: partially-approved

#134 Migration Guide > Filters の翻訳
  src/guide/migration/filters.md
Labels: PR: reviewed-approved

#145 Migration Guide > Inline Template Attribute の翻訳
  src/guide/migration/inline-template-attribute.md
Labels: PR: reviewed-approved

#146 Migration Guide > Slots Unification の翻訳
  src/guide/migration/slots-unification.md
Labels: PR: reviewed-approved

#143 Migration Guide > key attribute の翻訳
  src/guide/migration/key-attribute.md
Labels: PR: partially-approved

#139 Migration > Global API Treeshaking の翻訳
  src/guide/migration/global-api-treeshaking.md
Labels: PR: partially-approved
