Repository vuejs-jp/ja.vuejs.org, pull requests merged in 2021-06, with the labels that each got.

#374 Fix on guide/composition-api-setup.md
  src/guide/composition-api-setup.md
Labels: PR: reviewed-approved

#367 API Reference > Application Config の翻訳を追従
  src/api/application-config.md
Labels: PR: reviewed-approved

#371 API Reference > Application API の翻訳を追従
  src/api/application-api.md
Labels: PR: reviewed-approved

#403 guide/typescript-support.mdのtypoを修正（肩→型）
  src/guide/typescript-support.md
Labels: PR: reviewed-approved

#376 API Reference > Global API の翻訳を追従
  src/api/global-api.md
Labels: PR: reviewed-approved

#382 Add created hook to custom directives code example
  src/guide/migration/custom-directives.md
Labels: PR: reviewed-approved

#383 docs: Update key-attribute.md
  src/guide/migration/key-attribute.md
Labels: PR: reviewed-approved

#384 fix: prevent CodePens from stealing focus and scrolling the page
  src/guide/component-basics.md
  src/guide/component-dynamic-async.md
  src/guide/events.md
  src/guide/forms.md
  src/guide/list.md
Labels: PR: reviewed-approved

#385 fix: use method shorthands and switch indexOf to includes
  src/guide/component-props.md
Labels: PR: reviewed-approved

#386 docs: update recommended node version
  src/guide/ssr/getting-started.md
Labels: PR: reviewed-approved

#387 Add onActivated and onDeacitvated hooks to the list
  src/api/composition-api.md
  src/guide/composition-api-lifecycle-hooks.md
Labels: PR: reviewed-approved

#388 The description of this in setup is inconsistent with the source code
  src/guide/composition-api-introduction.md
Labels: PR: reviewed-approved

#391 docs: a few improvements
  src/guide/migration/attribute-coercion.md
  src/guide/migration/custom-directives.md
Labels: PR: reviewed-approved

#392 Update introduction.md
  src/guide/introduction.md
Labels: PR: reviewed-approved

#393 docs: elaborate on how style auto-prefixing works
  src/guide/class-and-style.md
Labels: PR: reviewed-approved

#394 Cookbook の翻訳を追従
  src/.vuepress/config.js
  src/.vuepress/public/images/breakpoint_hit.png
  src/.vuepress/public/images/breakpoint_set.png
  src/.vuepress/public/images/config_add.png
  src/.vuepress/public/images/devtools-timetravel.gif
  src/.vuepress/public/images/editable-svg-icons-sizes.png
  src/.vuepress/public/images/editable-svg-icons.jpg
  src/cookbook/automatic-global-registration-of-base-components.md
  src/cookbook/debugging-in-vscode.md
  src/cookbook/editable-svg-icons.md
  src/cookbook/index.md
Labels: PR: reviewed-approved

#395 API Reference > Options Data の翻訳を追従
  src/api/options-data.md
Labels: PR: reviewed-approved

#396 API Reference > Options DOM の翻訳を追従
  src/api/options-dom.md
Labels: PR: reviewed-approved

#398 Migration Guide > Migration Build の翻訳
  src/.vuepress/config.js
  src/guide/migration/array-refs.md
  src/guide/migration/async-components.md
  src/guide/migration/attribute-coercion.md
  src/guide/migration/attrs-includes-class-style.md
  src/guide/migration/children.md
  src/guide/migration/custom-directives.md
  src/guide/migration/custom-elements-interop.md
  src/guide/migration/data-option.md
  src/guide/migration/events-api.md
  src/guide/migration/filters.md
  src/guide/migration/functional-components.md
  src/guide/migration/global-api.md
  src/guide/migration/inline-template-attribute.md
  src/guide/migration/introduction.md
  src/guide/migration/keycode-modifiers.md
  src/guide/migration/listeners-removed.md
  src/guide/migration/migration-build.md
  src/guide/migration/mount-changes.md
  src/guide/migration/props-default-this.md
  src/guide/migration/render-function-api.md
  src/guide/migration/slots-unification.md
  src/guide/migration/transition-group.md
  src/guide/migration/v-bind.md
  src/guide/migration/v-if-v-for.md
  src/guide/migration/v-model.md
  src/guide/migration/v-on-native-modifier-removed.md
  src/guide/migration/vnode-lifecycle-events.md
  src/guide/migration/watch.md
Labels: PR: reviewed-approved

#404 Fix: broken gif url
  src/guide/state-management.md
Labels: PR: unreviewed

#405 Update custom-directive.md
  src/guide/custom-directive.md
Labels: PR: unreviewed

#406 feature: add Vue 3 vueschool links
  src/guide/class-and-style.md
  src/guide/computed.md
  src/guide/conditional.md
  src/guide/data-methods.md
  src/guide/events.md
  src/guide/forms.md
  src/guide/installation.md
  src/guide/list.md
Labels: PR: unreviewed

#407 fix: json format quotation
  src/guide/migration/data-option.md
Labels: PR: unreviewed

#410 chore: update partners contact info
  src/community/partners.md
Labels: PR: unreviewed

#411 fix: await router push in ssr server
  src/guide/ssr/routing.md
Labels: PR: unreviewed

#419 fix: update positioning in lifecycle diagram
  src/.vuepress/public/images/lifecycle.svg
Labels: PR: unreviewed

#422 Summary of changes for the 4th week of june
  src/.vuepress/public/images/sponsors/laravel.png
  src/.vuepress/public/images/sponsors/storyblok.png
  src/.vuepress/public/images/sponsors/storyblok.svg
  src/.vuepress/theme/data/patreon-sponsors.js
  src/guide/migration/attribute-coercion.md
  src/guide/migration/migration-build.md
Labels: PR: unreviewed

#421 3.1 Updates
  src/api/application-config.md
  src/api/built-in-components.md
  src/api/composition-api.md
  src/api/directives.md
  src/api/options-misc.md
  src/api/special-attributes.md
  src/guide/component-basics.md
  src/guide/migration/custom-elements-interop.md
  src/guide/migration/global-api.md
  src/style-guide/README.md
Labels: PR: reviewed-approved

#409 docs: add transition as root to the migration guide
  src/.vuepress/config.js
  src/guide/migration/transition-as-root.md
  src/guide/migration/transition-group.md
  src/guide/migration/transition.md
Labels: PR: reviewed-approved

#408 docs: add installation notes about compiler-sfc and bundlers
  src/guide/installation.md
Labels: PR: reviewed-approved

#428 chore: whitespace changes suggested by Prettier
  src/guide/migration/array-refs.md
  src/guide/single-file-component.md
  src/guide/teleport.md
Labels: PR: unreviewed

#185 style-guide Priority C の翻訳
  src/style-guide/README.md
Labels: PR: partially-approved

#430 スタイルガイドの未翻訳部分を追従
  src/style-guide/README.md
Labels: PR: unreviewed
