Repository vuejs-jp/ja.vuejs.org, pull requests merged in 2021-05, with the labels that each got.

#298 Guide > Components In-Depth > Props の翻訳を追従
  src/guide/component-props.md
Labels: PR: reviewed-approved

#299 Guide > Components In-Depth > Non-Prop Attributes の翻訳を追従
  src/guide/component-attrs.md
Labels: PR: reviewed-approved

#300 Guide > Components In-Depth > Custom Evnets の翻訳を追従
  src/guide/component-custom-events.md
Labels: PR: reviewed-approved

#301 Guide > Components In-Depth > Provide / inject の翻訳を追従
  src/guide/component-provide-inject.md
Labels: PR: reviewed-approved

#302 Guide > Componetns In-Depth > Dynamic & Async Components の翻訳を追従
  src/guide/component-dynamic-async.md
Labels: PR: reviewed-approved

#303 Guide > Components In-Depth > Handling Edge Cases の翻訳を追従
  src/guide/component-edge-cases.md
Labels: PR: reviewed-approved

#304 翻訳以外の追従
  README.md
  package.json
  src/.vuepress/components/common/vuemastery-video-modal.vue
  src/.vuepress/components/community/team/members.js
  src/.vuepress/config.js
  src/.vuepress/public/images/css-vs-js-ease.svg
  src/.vuepress/public/images/icons/android-icon-144x144.png
  src/.vuepress/public/images/icons/android-icon-192x192.png
  src/.vuepress/public/images/icons/android-icon-36x36.png
  src/.vuepress/public/images/icons/android-icon-48x48.png
  src/.vuepress/public/images/icons/android-icon-72x72.png
  src/.vuepress/public/images/icons/android-icon-96x96.png
  src/.vuepress/public/images/icons/apple-icon-114x114.png
  src/.vuepress/public/images/icons/apple-icon-120x120.png
  src/.vuepress/public/images/icons/apple-icon-144x144.png
  src/.vuepress/public/images/icons/apple-icon-152x152.png
  src/.vuepress/public/images/icons/apple-icon-180x180.png
  src/.vuepress/public/images/icons/apple-icon-57x57.png
  src/.vuepress/public/images/icons/apple-icon-60x60.png
  src/.vuepress/public/images/icons/apple-icon-72x72.png
  src/.vuepress/public/images/icons/apple-icon-76x76.png
  src/.vuepress/public/images/icons/apple-icon-precomposed.png
  src/.vuepress/public/images/icons/apple-icon.png
  src/.vuepress/public/images/icons/bacancy_technology.png
  src/.vuepress/public/images/icons/favicon-16x16.png
  src/.vuepress/public/images/icons/favicon-32x32.png
  src/.vuepress/public/images/icons/favicon-96x96.png
  src/.vuepress/public/images/icons/favicon.ico
  src/.vuepress/public/images/icons/ms-icon-144x144.png
  src/.vuepress/public/images/icons/ms-icon-150x150.png
  src/.vuepress/public/images/icons/ms-icon-310x310.png
  src/.vuepress/public/images/icons/ms-icon-70x70.png
  src/.vuepress/public/images/sponsors/laravel.png
  src/.vuepress/public/manifest.json
  src/.vuepress/theme/components/Navbar.vue
  src/.vuepress/theme/components/Newsletter.vue
  yarn.lock
Labels: PR: reviewed-approved

#307 Guide > Enter & Leave Transitions の翻訳を追従
  src/guide/transitions-enterleave.md
Labels: PR: reviewed-approved

#305 Guide > Scaling Up > Routing の翻訳を追従
  src/guide/routing.md
Labels: PR: reviewed-approved

#306 Guide > Scaling Up > State Management の翻訳を追従
  src/guide/state-management.md
Labels: PR: reviewed-approved

#310 Guide > Tooling > Testing の翻訳を追従
  src/guide/testing.md
Labels: PR: reviewed-approved

#311 Guide > Reusability & Composition > Plugins の翻訳を追従
  src/guide/plugins.md
Labels: PR: reviewed-approved

#312 Guide > Transitions & Animation > Overview の翻訳を追従
  src/guide/transitions-overview.md
Labels: PR: reviewed-approved

#308 Guide > Reusability & Composition > Render functions の翻訳を追従
  src/guide/render-function.md
Labels: PR: reviewed-approved

#309 Guide > Tooling > Single File Components の翻訳を追従
  src/guide/single-file-component.md
Labels: PR: reviewed-approved

#313 Guide > Advanced Guides > Reactivity Fundamentals の翻訳を追従
  src/guide/reactivity-fundamentals.md
Labels: PR: reviewed-approved

#315 Guide > Advanced Guides > Reactivity > Computed and Watch の翻訳を追従
  src/guide/reactivity-computed-watchers.md
Labels: PR: reviewed-approved

#316 Guide > Advanced Guides > Rendering Mechanisms and Optimizations の翻訳を追従
  src/guide/optimizations.md
Labels: PR: reviewed-approved

#317 Guide > Advanced Guides > Change Detection Ceveats in Vue 2 の翻訳を追従
  src/guide/change-detection.md
Labels: PR: reviewed-approved

#314 Guide > Advanced Guides > Reactivity in Depth の翻訳を追従
  src/guide/reactivity.md
Labels: PR: reviewed-approved

#318 Guide > Transitions & Animation > List Transitions の翻訳を追従
  src/guide/transitions-list.md
Labels: PR: reviewed-approved

#319 Guide > Scaling Up > Server-Side Rendering の翻訳を追従
  src/.vuepress/config.js
  src/guide/ssr.md
  src/guide/ssr/build-config.md
  src/guide/ssr/getting-started.md
  src/guide/ssr/hydration.md
  src/guide/ssr/introduction.md
  src/guide/ssr/routing.md
  src/guide/ssr/server.md
  src/guide/ssr/structure.md
  src/guide/ssr/universal.md
Labels: PR: reviewed-approved

#320 Migration from Vue 2 > v-model の翻訳を追従
  src/guide/migration/attrs-includes-class-style.md
  src/guide/migration/children.md
  src/guide/migration/custom-directives.md
  src/guide/migration/custom-elements-interop.md
  src/guide/migration/data-option.md
  src/guide/migration/emits-option.md
  src/guide/migration/filters.md
  src/guide/migration/functional-components.md
  src/guide/migration/key-attribute.md
  src/guide/migration/v-if-v-for.md
  src/guide/migration/v-model.md
  src/guide/migration/watch.md
Labels: PR: reviewed-approved

#323 Guide > Server-Side Rendering Guide > Universal の翻訳
  src/guide/ssr/universal.md
Labels: PR: reviewed-approved

#321 Guide > Server-Side Rendering Guide > Introduction の翻訳
  src/guide/ssr/introduction.md
Labels: PR: reviewed-approved

#325 Guide > Server-Side Rendering Guide > Source Code Structure の翻訳
  src/guide/ssr/structure.md
Labels: PR: reviewed-approved

#322 Guide > Server-Side Rendering Guide > Getting Started の翻訳
  src/guide/ssr/getting-started.md
Labels: PR: unreviewed

#348 chore: tidy up the markdown tables(テーブルを揃える)
  src/guide/a11y-basics.md
  src/guide/composition-api-lifecycle-hooks.md
  src/guide/migration/global-api.md
Labels: PR: reviewed-approved

#350 Guide > Reactivity の typo 修正
  src/guide/reactivity.md
Labels: PR: reviewed-approved

#326 sync with upstream vuepress files
  README.md
  assets/lifecycle-diagram.svg
  assets/scoped-slot-diagram.svg
  assets/slot-render-diagram.svg
  package.json
  src/.vuepress/components/MigrationBadges.vue
  src/.vuepress/components/guide/contributing/translations-data.js
  src/.vuepress/components/guide/contributing/translations.vue
  src/.vuepress/components/search/index.vue
  src/.vuepress/components/support/Coins.vue
  src/.vuepress/config.js
  src/.vuepress/public/images/coin-bch.png
  src/.vuepress/public/images/coin-btc.png
  src/.vuepress/public/images/coin-eth.png
  src/.vuepress/public/images/coin-ltc.png
  src/.vuepress/theme/components/BuySellAds.vue
  src/.vuepress/theme/components/CarbonAds.vue
  src/.vuepress/theme/components/Home.vue
  src/.vuepress/theme/layouts/Layout.vue
  src/.vuepress/theme/styles/index.styl
  src/README.md
  src/community/join.md
  src/guide/contributing/translations.md
  src/search/README.md
  yarn.lock
Labels: PR: reviewed-approved

#327 Docs > Examples の翻訳を追従
  src/examples/elastic-header.md
  src/examples/markdown.md
  src/examples/todomvc.md
Labels: PR: reviewed-approved

#346 feat: add che-tsumi github action
  .github/workflows/che-tsumi.yaml
Labels: PR: partially-approved

#349 Guide > Server-Side Rendering Guide > Build Configuration の翻訳
  src/guide/ssr/build-config.md
Labels: PR: reviewed-approved

#351 Guide > Server-Side Rendering Guide > Server Configuration の翻訳
  src/guide/ssr/server.md
Labels: PR: reviewed-approved

#352 Guide > Server-Side Rendering Guide > Routing and Code-Splitting の翻訳
  src/guide/ssr/routing.md
Labels: PR: reviewed-approved

#355 Guide > Server-Side Rendering Guide > Client Side Hydration の翻訳
  src/guide/ssr/hydration.md
Labels: PR: reviewed-approved

#356 v-forとv-ifを正しい順番に修正
  src/style-guide/README.md
Labels: PR: reviewed-approved

#365 Fix typo on component-custom-events page
  src/guide/component-custom-events.md
Labels: PR: reviewed-approved

#359 Docs > Migration from Vue 2 の細かな差分
  src/guide/migration/async-components.md
  src/guide/migration/custom-directives.md
  src/guide/migration/filters.md
  src/guide/migration/introduction.md
  src/guide/migration/listeners-removed.md
Labels: PR: reviewed-approved

#363 Docs > Essentials Guide の更新
  src/guide/composition-api-provide-inject.md
  src/guide/introduction.md
  src/guide/typescript-support.md
Labels: PR: reviewed-approved

#364 chore: remove upstream sync github action
  .github/workflows/sync.yaml
Labels: PR: unreviewed

#369 Fix typo
  src/guide/composition-api-introduction.md
Labels: PR: reviewed-approved

#370 Fix markdown link format in mixins page
  src/guide/mixins.md
Labels: PR: reviewed-approved
